[package]
name = "day6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
once_cell = "1"
processor = { path = "../processor" }
regex = "1"
string-builder = "0.2"
substring = "1"
