[package]
name = "day15"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
linked-hash-map = "0"
once_cell = "1"
processor = { path = "../processor" }
regex = "1"
substring = "1"
